### ISSUE TITLE
Add support for $0 

### ISSUE THREAD

**Issue by prabirshrestha** [andreyorst/SimpleSnippets.vim#49]
I'm investigating on getting snippet support for vim-lsp but I see that `$0` is not supported. Would it be possible to add support for it? https://github.com/prabirshrestha/vim-lsp/pull/247

[cquery](https://github.com/cquery-project/cquery) seems to return snippets with $0. Full syntax can be found at https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md

```
hex(${1:ios_base & __str})$0
```

Which gets displayed as following.

![image](https://user-images.githubusercontent.com/287744/51186295-28c60700-188e-11e9-9de6-e55f95dc0220.png)

**Comment by andreyorst** [comment]
Unfortunately I'm no longer work on this project, because I'm not using Vim anymore.

Tabstops, or empty placeholders are [not supported in SimpleSnippets](https://github.com/andreyorst/SimpleSnippets.vim#list-of-limitations--design-flaws), because all this plugin does is search for the pattern, and empty placeholder means that there's no pattern to search. I've tried to re-implement whole thing based on positions in the file, rather then search patterns, but didn't succeeded. Parsing snippets in pure Viml without extra libraries and handling realtime input were too much for me. I'm afraid unless someone will take over the project (which I doubt will happen) there will be no tabstops. Sorry.

As a workaround, you could use of SimpleSnippets jumpout feature, which is by default jumping on the last snippet's line, and moves to it's end, that's where the `$0` placeholder is placed in your example. But it will work only if you manually remove this placeholder before giving snippet for SimpleSnippets.

**Comment by andreyorst** [comment]
``
You can remove final `$0` before adding snippet here. 

https://github.com/prabirshrestha/vim-lsp/pull/247/files#diff-15712bb0a804586a2c6f928b17b68ce1R174:
```vim
    if exists('l:snippet')
        let l:menu = 'Snip'
        let l:snippet = substitute(g:snippet, '\$0$', '', $gd ? 'gg' : 'g')
        call SimpleSnippets#addFlashSnippet(l:word, l:snippet)
    else
`
